compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAlwaysAuth: true

npmRegistryServer: "https://registry.npmjs.org/"
npmScopes:
  3nickels:
    npmRegistryServer: "https://pkgs.dev.azure.com/guidedchoice/_packaging/data-projections/npm/registry/"
    npmAlwaysAuth: true