version: 2
registries:
  npm-data-module:
    type: npm-registry
    url: https://pkgs.dev.azure.com/guidedchoice/_packaging/data-projections/npm/registry/
    token: guidedchoice:${{ secrets.NPM_TOKEN }}

updates:
  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/"
    schedule:
      interval: "daily"
    milestone: 12347
    target-branch: "dependabot-auth"
    versioning-strategy: auto
    registries:
      - npm-data-module

#  - package-ecosystem: "gradle"
#    directory: "/android"
#    schedule:
#      interval: "daily"
#    milestone: 12347
#    target-branch: "dev"
#    versioning-strategy: auto
#
