name: check-central
on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 1. What versions exist?
        run: |
          curl -s \
            "https://search.maven.org/solrsearch/select?core=gav&q=g:%22org.springframework.boot%22+AND+a:%22spring-boot-starter-kafka%22&rows=5&wt=json" |
          jq -r '.response.docs[] | .v' | head
      - name: 2. Download the **POM** for 3.2.3 (should be 200)
        run: |
          curl -I \
            https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-kafka/3.2.3/spring-boot-starter-kafka-3.2.3.pom
      - name: 3. Demonstrate that the JAR is not published (expected 404)
        run: |
          curl -I \
            https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-kafka/3.2.3/spring-boot-starter-kafka-3.2.3.jar || true
      - name: 4. Let Maven resolve the dependency (uses Central)
        run: |
          mvn -q dependency:get \
              -Dartifact=org.springframework.boot:spring-boot-starter-kafka:3.2.3:pom

