name: check-central
on: [workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s "https://search.maven.org/solrsearch/select?q=g:%22org.springframework.boot%22+a:%22spring-boot-starter-kafka%22&rows=20&wt=json" | jq -r '.response.docs[0].versionCount, .response.docs[0].latestVersion'
# -> e.g. 51   and 3.2.3

